[package]
name    = "glyph_geometry_2d"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck   = "1.19.0"
cgmath     = "0.18.0"
env_logger = "0.11.5"
wgpu       = "22.1.0"
wgsim      = { path = "../../lib/wgsim" }
pollster   = "0.3.0"
rand       = "0.8.5"
meshtext   = "0.3.1"
