[package]
name    = "compute_bitonic_sort"
version = "0.1.0"
edition = "2021"

[dependencies]
env_logger        = "0.11.5"
wgpu              = "22.1.0"
wgsim             = { path = "../../lib/wgsim" }
futures-intrusive = "0.5.0"
bytemuck          = "1.19.0"
num-traits        = "0.2.19"
